### ISSUE TITLE
Legacy API lifecycle.

### ISSUE THREAD

**Issue by trinopoty** [linode/linode-api-docs#169]
Would it be possible to know or add the legacy (v3) API lifecycle (end of support date)?
I know new stuff should use the new API but we certainly have existing tools that use the legacy API and it would be good to know how long we have to switch everything over to the new API.

**Comment by hzoppetti** [comment]
Hello @trinopoty ending support for API v3 is not on our roadmap currently and we will continue supporting it for now. If that changes we will make sure you have plenty of notice. To keep up-to-date with news of API and other products, you can subscribe to our blog and newsletter. Thank you for inquiring!

**Comment by displague** [comment]
@trinopoty @hzoppetti @Dorthu @mahemoff
https://www.linode.com/2019/11/18/notice-legacy-linode-manager-users/

>  Additionally, we will continue to support APIv3 and the APIv3-based CLI beyond January 31, 2020.

The bit about [APIv3-based CLI](https://github.com/linode/cli) is interesting, because that has been deprecated for a while and [new issues being filed against it are being closed](https://github.com/linode/linode-cli/issues/163#issuecomment-561767536).

**Comment by Dorthu** [comment]
To be fair, that issue was opened against the _new_ CLI referencing the old one - if it had been opened on Linode/cli it wouldn't have been closed.

**Comment by displague** [comment]
@Dorthu The old CLI is an archived project.  Issues can not be opened on it.

**Comment by hzoppetti** [comment]
I think the more accurate language would have been to say that we will continue to make these products available beyond January 31st 2020. They are not scheduled for immediate retirement in the current roadmap. It is true that both projects have been archived or deprecated, and we encourage users to migrate to v4 at some point. That being said, again, we will give notice when we do plan to retire them via the blog and newsletter.
