### ISSUE TITLE
Request for contribution guidelines

### ISSUE THREAD

**Issue by eatonphil** [linode/linode-api-docs#36]
The major question is: which branch do I make a PR against? And by extension, what is the release model? Any other info would probably also be useful for anyone interested in contributing.

**Comment by rjstires** [comment]
Hi Phil! the new api-docs and components repos are still very new and we're fleshing out contributing and standards.

Keep checking back! 👍

**Comment by displague** [comment]
Unrelated, but related: We've received some API docs-vs-reality bug reports on the linode/manager repo since the split.  We have to make sure we've updated the contribution and feedback documentation to point contributors in the right direction with respect to that.
