### ISSUE TITLE
issues in openapi spec

### ISSUE THREAD

**Issue by torabidm** [linode/linode-api-docs#362]
a couple of issues in the openapi spec file v.4.80.0 .. thought you might like to have a second look:

oauth2 scopes used without declaration in securitySchemes section:
		object_storage:read_only
		firewall:read_only
		object_storage:read_write
		maintenance:read_only
		firewall:read_write
		firewalls:read_only

and, scope called "events:read_only" controlling POST, looks like a typo?
https://github.com/linode/linode-api-docs/blob/544b09995f6fc8808b86c244d2e1ca71cc11fb72/openapi.yaml#L752

**Comment by bbiggerr** [comment]
Thanks for the report! We've addressed these issues in v4.81.0. The "events:read_only" scope for the Event Mark as Seen endpoint was intended. While it is a POST endpoint, read_only is the minimal grant required for clients to view events, which are subsequently marked as seen on the backend. We did notice that the x-linode-grant was improperly stated as read_write for this endpoint, so we fixed it to read_only as well.
